# Generated by Django 4.1.3 on 2022-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastemanagement',
            name='agentname',
            field=models.CharField(max_length=200),
        ),
    ]
