# Generated by Django 4.1.3 on 2022-11-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_wastemanagement_agentname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastemanagement',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wastemanagement',
            name='time',
        ),
    ]
