# Generated by Django 4.1.3 on 2022-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_wastemanagement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastemanagement',
            name='customername',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
