# Generated by Django 4.1.3 on 2022-11-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_wastemanagement_customername_wastemanagement_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=200, null=True)),
                ('customerlocation', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='wastemanagement',
            name='agentno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.workermanagement'),
        ),
    ]
