# Generated by Django 4.1.3 on 2022-11-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_workermanagement_wastemanagement_agentno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workermanagement',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='workermanagement',
            name='customerlocation',
        ),
        migrations.AddField(
            model_name='workermanagement',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workermanagement',
            name='customeraddress',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workermanagement',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='WasteManagement',
        ),
    ]
