# Generated by Django 4.1.3 on 2022-11-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_workermanagement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermanagement',
            name='id',
        ),
        migrations.AddField(
            model_name='workermanagement',
            name='customeremail',
            field=models.EmailField(default='amilpa2020@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
    ]
