# Generated by Django 4.1.3 on 2022-11-25 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_workermanagement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermanagement',
            name='customeremail',
        ),
        migrations.AlterField(
            model_name='workermanagement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workermanagement',
            name='customeraddress',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workermanagement',
            name='customername',
            field=models.CharField(default='hello', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workermanagement',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
