# Generated by Django 4.1.3 on 2022-11-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_workermanagement_customeremail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermanagement',
            name='customeremail',
            field=models.EmailField(default='amilpa2020@gmail.com', max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workermanagement',
            name='customername',
            field=models.CharField(max_length=200),
        ),
    ]
